test_that("plot is generated if plot = TRUE", {
  mock <- mockery::mock()
  mockery::stub(run_model, "sir_plot", mock)
  run_model(1:100, plot = TRUE)
  mockery::expect_called(mock, 1)
})

test_that("plot is not generated by default", {
  mock <- mockery::mock()
  mockery::stub(run_model, "sir_plot", mock)
  run_model(1:100)
  mockery::expect_called(mock, 0)
})
