## Automatically generated by odin 1.2.1 - do not edit
sir_deterministic_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "sir_deterministic_rhs_dde"),
    dll = "sir",
    user = c("beta", "I_ini", "S_ini", "sigma"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("sir_deterministic_rhs_dde", package = "sir")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("sir_deterministic_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "sir")
    },

    update_metadata = function() {
      meta <- .Call("sir_deterministic_metadata", private$ptr,
                    PACKAGE = "sir")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("sir_deterministic_create", user, PACKAGE = "sir")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/sir_deterministic.json", mustWork = TRUE,
                             package = "sir")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("sir_deterministic_set_user", private$ptr, user, PACKAGE = "sir")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("sir_deterministic_initial_conditions", private$ptr, step, PACKAGE = "sir")
    },

    rhs = function(step, y) {
      .Call("sir_deterministic_rhs_r", private$ptr, step, y, PACKAGE = "sir")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("sir_deterministic_contents", private$ptr, PACKAGE = "sir")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


sir_deterministic <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("sir_deterministic")
  sir_deterministic_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(sir_deterministic) <- "odin_generator"
attr(sir_deterministic, "generator") <- sir_deterministic_
sir_stochastic_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "sir_stochastic_rhs_dde"),
    dll = "sir",
    user = c("beta", "I_ini", "nsim", "S_ini", "sigma"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("sir_stochastic_rhs_dde", package = "sir")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("sir_stochastic_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "sir")
    },

    update_metadata = function() {
      meta <- .Call("sir_stochastic_metadata", private$ptr,
                    PACKAGE = "sir")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("sir_stochastic_create", user, PACKAGE = "sir")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/sir_stochastic.json", mustWork = TRUE,
                             package = "sir")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("sir_stochastic_set_user", private$ptr, user, PACKAGE = "sir")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("sir_stochastic_initial_conditions", private$ptr, step, PACKAGE = "sir")
    },

    rhs = function(step, y) {
      .Call("sir_stochastic_rhs_r", private$ptr, step, y, PACKAGE = "sir")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("sir_stochastic_contents", private$ptr, PACKAGE = "sir")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


sir_stochastic <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("sir_stochastic")
  sir_stochastic_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(sir_stochastic) <- "odin_generator"
attr(sir_stochastic, "generator") <- sir_stochastic_
