#' @title
#' run stochastic SIR model
#' @description
#' runs the stochastic SIR model for given times and parameters
#'
#' @param tt vector of times
#' @param beta rate of infection
#' @param sigma rate of recovery
#' @param S_ini initial number susceptible
#' @param I_ini initial number infected
#' @export
run_model <- function(tt, beta = 0.2, sigma = 0.1, S_ini = 1000, I_ini = 1, plot = FALSE) {
  mod <- sir_stochastic$new(user = list(beta = beta, sigma = sigma, S_ini = S_ini, I_ini = I_ini))
  y <- mod$run(tt)
  if (plot) {
    sir_plot(y)
  }
  return(y)
}

#' @title
#' run deterministic SIR model
#' @description
#' runs the deterministic SIR model for given times and parameters
#'
#' @param tt vector of times
#' @param beta rate of infection
#' @param sigma rate of recovery
#' @param S_ini initial number susceptible
#' @param I_ini initial number infected
#' @export
run_model_deterministic <- function(tt, beta = 0.2, sigma = 0.1, S_ini = 1000, I_ini = 1, plot = FALSE) {
  mod <- sir_deterministic$new(user = list(beta = beta, sigma = sigma, S_ini = S_ini, I_ini = I_ini))
  y <- mod$run(tt)
  if (plot) {
    sir_plot(y)
  }
  return(y)
}

#' @title
#' plot output from an SIR model run
#'
#' @param res object generated by running sir::run_model or sir::run_model_deterministic
#' @export
sir_plot <- function(res) {
  matplot(res[, 1], res[, -1], type = "l", xlab = "Time", ylab = "Population")
  legend("right", colnames(res)[-1], col = 2:4, fill = 2:4)
}
