#' @title
#' run stochastic SIR model
#' @description
#' runs the stochastic SIR model for given times and parameters
#'
#' @param tt vector of times
#' @param nsim number of realisations to include
#' @param beta rate of infection
#' @param sigma rate of recovery
#' @param S_ini initial number susceptible
#' @param I_ini initial number infected
#' @param plot boolean, optionally plot results
#' @export
run_model <- function(tt, nsim = 100, beta = 0.2, sigma = 0.1, S_ini = 1000, I_ini = 1, plot = FALSE) {
  mod <- sir_stochastic$new(user = list(nsim = nsim, beta = beta, sigma = sigma, S_ini = S_ini, I_ini = I_ini))
  y <- mod$run(tt)
  if (plot) {
    sir_plot(y)
  }
  return(y)
}

#' @title
#' run deterministic SIR model
#' @description
#' runs the deterministic SIR model for given times and parameters
#'
#' @param tt vector of times
#' @param beta rate of infection
#' @param sigma rate of recovery
#' @param S_ini initial number susceptible
#' @param I_ini initial number infected
#' @param plot boolean, optionally plot results
#' @export
run_model_deterministic <- function(tt, beta = 0.2, sigma = 0.1, S_ini = 1000, I_ini = 1, plot = FALSE) {
  mod <- sir_deterministic$new(user = list(beta = beta, sigma = sigma, S_ini = S_ini, I_ini = I_ini))
  y <- mod$run(tt)
  if (plot) {
    sir_plot(y)
  }
  return(y)
}

#' @title
#' plot output from an SIR model run
#'
#' @param res object generated by running sir::run_model or sir::run_model_deterministic
#' @param ... optional arguments to pass to base plot() function
#' @export
sir_plot <- function(res, ...) {
  params <- list(...)
  if (is.null(params$col)) {
    sir_col <- c("#8c8cd9", "#cc0044", "#999966")
    params$col <- rep(sir_col, each = (ncol(res) - 1) / 3)
  }
  if (is.null(params$type)) {
    params$type <- "l"
  }
  if (is.null(params$lty)) {
    params$lty <- 1
  }
  if (is.null(params$xlab)) {
    params$xlab <- "Time"
  }
  if (is.null(params$ylab)) {
    params$ylab <- "Population"
  }
  do.call(matplot, c(list(res[, 1], res[, -1]), params))
  legend("left", legend = c("S", "I", "R"), col = sir_col, lwd = 1)
  invisible(NULL)
}

#' @title
#' add output to existing plot from an SIR model run
#'
#' @param res object generated by running sir::run_model or sir::run_model_deterministic
#' @param ... optional arguments to pass to base plot() function
#' @export
sir_lines <- function(res, ...) {
  params <- list(...)
  if (is.null(params$col)) {
    sir_col <- c("#8c8cd9", "#cc0044", "#999966")
    params$col <- rep(sir_col, each = (ncol(res) - 1) / 3)
  }
  if (is.null(params$lty)) {
    params$lty <- 1
  }
  do.call(matlines, c(list(res[, 1], res[, -1]), params))
  invisible(NULL)
}
